name: build site
on:
  workflow_dispatch:
    inputs:
      siteUri:
        description: 'Site URI'
        required: true
      kacheryZone:
        description: 'Kachery zone'
        required: false
        default: 'default'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd python && pip install -r requirements.txt
      - name: Build site
        run: |
          cd python && python build_site.py
        env:
          SITE_URI: ${{ github.event.inputs.siteUri }}
          KACHERY_ZONE: ${{ github.event.inputs.kacheryZone }}