name: prepare site
on:
  workflow_dispatch:
    inputs:
      siteUri:
        description: 'Site URI'
        required: true
      kacheryZone:
        description: 'Kachery zone'
        required: false
        default: 'default'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd python && pip install -r requirements.txt
      - name: Prepare site
        run: |
          cd python && python prepare_site.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          SITE_URI: ${{ github.event.inputs.siteUri }}
          KACHERY_ZONE: ${{ github.event.inputs.kacheryZone }}